### ISSUE TITLE
srmbg should send a real webp, not just rename the file

### ISSUE THREAD

**Issue by FrayxRulez** [sandy1709/catuserbot#119]
Hey, it seems that srmbg command is just renaming the original image from png to webp, and this causes compatibility issues with some clients, that will just display a blank square.
In addition to this, the command seems not to preserve the original image size (got scaled to 500x500) causing more compatibility issues with other clients.

**Comment by sandy1709** [comment]
Thank you
I didn't know this will change this by using pil library

**Comment by sandy1709** [comment]
it was fixed in version 2.9.2
