### ISSUE TITLE
Feature Request: More customization and auto posting of reddit.py

### ISSUE THREAD

**Issue by mubashir-rehman** [sandy1709/catuserbot#203]
What is available:
currently only random picture from a subreddit can be posted.
What should be added:
Ability to run the command such that it posts to selected channels/chats after intervals from options like tops 10 posts or hot 9 posts.
What alternatives are available:
https://github.com/aliparlakci/bulk-downloader-for-reddit does a pretty good job for one time downloads with great configuration options.
https://github.com/Fillll/reddit2telegram does provide the required features but it is not available as a userbot plugin or heruko app.

**Comment by CjConvento** [comment]
sir how can I update the userbot from railway without losing data

Thank you,
DangCJ

**Comment by sandy1709** [comment]
@CjConvento 
![image](https://user-images.githubusercontent.com/58665444/134805023-6b38a81a-c3f7-465b-b350-5bc6ae6bd1bc.png)
click on fetch merge after clicking on fetch upstream

**Comment by CjConvento** [comment]
Thank you @mrconfused

**Comment by CjConvento** [comment]
so sur I have to redeploy again?

**Comment by sandy1709** [comment]
railway auto-deploys i guess after any change in github repo . 

i think so ( i don't know much about railway)
