### ISSUE TITLE
cant deploy to heroku

### ISSUE THREAD

**Issue by heyxferdi** [sandy1709/catuserbot#244]
cant deploy to heroku
because of this:
![image](https://user-images.githubusercontent.com/87966788/135201785-acfd3a71-ecf7-4e87-bf64-b7ad2960e1e2.png)

**Comment by sandy1709** [comment]
![image](https://user-images.githubusercontent.com/58665444/135719767-a7788fdd-882d-4ca4-b2bf-b3e4f8941039.png)
Read that https://github.com/Mr-confused/nekopack
