### ISSUE TITLE
Upload folder as tree.

### ISSUE THREAD

**Issue by Deshdeepak1** [sandy1709/catuserbot#97]
The files when uploading folder are uploaded all together. Wouldn't it be better if they are uploaded in tree format.
For e.g. if this is tree in the server, 

- /dir1/dir2/dir3 
                         - dir4
                              - f1
                          - dir5
                              - dir6 
                                  - f2
                              - f3
                           - f4
and if we want to upload entire dir3, it should we uploaded as
dir3 (as msg)
dir3/dir4 (as msg)
f1 (as file)
dir3/dir4 (as msg)
dir3/dir5 (as msg)
dir3/dir5/dir6 (as msg)
f2 (as file)
dir3/dir5/dir6 (as msg)
f3 (as file)
dir3/dir5 (as msg)
f4 (as file)
dir3 (as msg)
Should I make aPR of that ?

**Comment by sandy1709** [comment]
Good if you can do then send pr

**Comment by Deshdeepak1** [comment]
Will try. I have already did it in pyrogram. 
https://github.com/DaruaraFriends/userbot/blob/master/ubot/plugins/upload.py
Have you tried recently to use your userbot locally , I am just getting errors and errors. Or it just for Heroku.

**Comment by sandy1709** [comment]
Good thanks for suggestion mee to will try 
Actually i never tried using it locally by end of this month will try my best to make it to host locally

**Comment by Deshdeepak1** [comment]
I did create a PR.
https://github.com/sandy1709/catuserbot/pull/99
Also your uploadir has issues with thumbs , ever  try uploading folder with mp4s .

**Comment by sandy1709** [comment]
yaa thq

**Comment by Deshdeepak1** [comment]
Thanks for the merge. Will you kindly add hacktoberfest-accepted label.

**Comment by sandy1709** [comment]
i dont have idea about that hacktoberfest bro

**Comment by Deshdeepak1** [comment]
Just go to the right of this PR . You will see the label option . Click on its setting and type hacktoberfest-accepted . Thanks Anyway.

**Comment by Deshdeepak1** [comment]
Or just add hactoberfest label in your repo, from main page. But beaware it might increase spam.
